<?php

$file= "notes.txt";

if(file_exists($file)){unlink($file)
	
	
	/*if(	rename($file, "new_file.txt")){
		
		echo "Succesfully renamed";
		
	}else{
			echo "unSuccesfully ";
		
	}
	
	
	*/
	
}else{
	
	echo "This file is non exixtent";





/*if(file_exists($file)){
	
	
	if(	rename($file, "new_file.txt")){
		
		echo "Succesfully renamed";
		
	}else{
			echo "unSuccesfully ";
		
	}
	
	
	
	
}else{
	
	echo "This file is non exixtent";
}*/



?>